# TCL File Generated by Component Editor 18.1
# Fri Jul 18 23:01:55 CEST 2025
# DO NOT MODIFY


# 
# customTimerPeripheral "customTimerPeripheral" v1.0
#  2025.07.18.23:01:55
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module customTimerPeripheral
# 
set_module_property DESCRIPTION ""
set_module_property NAME customTimerPeripheral
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME customTimerPeripheral
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file customTimerPeripheral.sv SYSTEM_VERILOG PATH customTimerPeripheral.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point timer_mm_slave
# 
add_interface timer_mm_slave avalon end
set_interface_property timer_mm_slave addressUnits WORDS
set_interface_property timer_mm_slave associatedClock clock
set_interface_property timer_mm_slave associatedReset reset
set_interface_property timer_mm_slave bitsPerSymbol 8
set_interface_property timer_mm_slave bridgedAddressOffset 0
set_interface_property timer_mm_slave burstOnBurstBoundariesOnly false
set_interface_property timer_mm_slave burstcountUnits WORDS
set_interface_property timer_mm_slave explicitAddressSpan 0
set_interface_property timer_mm_slave holdTime 0
set_interface_property timer_mm_slave linewrapBursts false
set_interface_property timer_mm_slave maximumPendingReadTransactions 0
set_interface_property timer_mm_slave maximumPendingWriteTransactions 0
set_interface_property timer_mm_slave readLatency 0
set_interface_property timer_mm_slave readWaitTime 1
set_interface_property timer_mm_slave setupTime 0
set_interface_property timer_mm_slave timingUnits Cycles
set_interface_property timer_mm_slave writeWaitTime 0
set_interface_property timer_mm_slave ENABLED true
set_interface_property timer_mm_slave EXPORT_OF ""
set_interface_property timer_mm_slave PORT_NAME_MAP ""
set_interface_property timer_mm_slave CMSIS_SVD_VARIABLES ""
set_interface_property timer_mm_slave SVD_ADDRESS_GROUP ""

add_interface_port timer_mm_slave timer_mm_slave_address address Input 1
add_interface_port timer_mm_slave timer_mm_slave_read read Input 1
add_interface_port timer_mm_slave timer_mm_slave_readdata readdata Output 32
add_interface_port timer_mm_slave timer_mm_slave_write write Input 1
add_interface_port timer_mm_slave timer_mm_slave_writedata writedata Input 32
set_interface_assignment timer_mm_slave embeddedsw.configuration.isFlash 0
set_interface_assignment timer_mm_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment timer_mm_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment timer_mm_slave embeddedsw.configuration.isPrintableDevice 0

